name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        
    - name: Run tests
      run: |
        python test.py  # Запуск тестов из файла test.py

    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ./test-results

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
    - name: Download test results
      uses: actions/download-artifact@v2
      with:
        name: test-results
        path: ./test-results
